### ISSUE TITLE
Refactor this repo

### ISSUE THREAD

**Issue by ybressler** [checkifcovid/data-science-experiments#1]
This should be moved to `Machine Learning` and placed in a proper directory.

**Comment by rashnil-git** [comment]
@ybressler : I have updated the board and used the same project as there was nothing in that project. https://github.com/checkifcovid/Data-processing-/projects/1

We can use the same for our project planning and tickets.

This is the ticket I created for you to refactor the repo. Feel free to add more tickets to the board in to-do so we can pick them and start working on them.

**Comment by ybressler** [comment]
Created directory `Archive` + Now operating in `V2`.
